name: Tests
run-name: Tests

on:
  workflow_dispatch:
  pull_request: 
    branches: 
      - "**"
    paths: 
      - test-virtuve/**
  push:
    branches:
      - main
    paths: 
      - test-virtuve/**
  
concurrency: 
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
  
jobs:
  prisma-adapter-tests:
    timeout-minutes: 15
    runs-on: ubuntu:latest
    defaults:
      run:
        working-directory: packages/prisma-db-adapter
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: random
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache-dependency-path: "**/**/pnpm-lock.yaml"
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
  
      - name: Apply migrations
        run: pnpm run db:migrate-prod

      - name: Run integration tests
        run: pnpm run test:i